modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/EnvyWare/EnvySTS"

[[mods]]
modId="envysts"
version="2.3.0"
displayName="EnvySTS"
displayURL="https://github.com/EnvyWare"
credits="Envyful"
authors="https://github.com/EnvyWare"
description='''
EnvySTS
'''

[[dependencies.envysts]]
modId="forge"
mandatory=true
versionRange="[48.0.30,)"
ordering="NONE"
side="BOTH"

[[dependencies.envysts]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"