modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/EnvyWare/EnvySTS"

[[mods]]
modId="envysts"
version="2.2.0"
displayName="EnvySTS"
displayURL="https://github.com/EnvyWare"
credits="Envyful"
authors="https://github.com/EnvyWare"
description='''
EnvySTS
'''

[[dependencies.envysts]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.envysts]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"